package MyProjects;

import java.util.Scanner;

public class SumofGivenNumbers {
	
	int sum=0;
	
	SumofGivenNumbers() {   //constructor 
	int n,m;
	Scanner s= new Scanner (System.in);
	m=s.nextInt();
	int a[]= new int[m];
	
	for (int i=0;i<m;i++) {
		n=(int) (Math.random() * 10);//random input generated by system 
		//n=s.nextInt(); user input
		a[i]=n;
		
		if (m>0) {	
		if(i==(m-1)) {
			System.out.println(n);
			break;
			}
		System.out.print(n+",");
		}		
	}
	
	for (int j=0;j<=a.length-1;j++) {
		
		sum=sum+a[j];
		
	 } 
	s.close();//input part over
	}
	void diplay() {
		
		System.out.println("Sum of given numbers:"+sum);
	}
	public static void main(String args[]) {
		
		SumofGivenNumbers s1=new SumofGivenNumbers();
		
		s1.diplay();
	}
}
